---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oadp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: oadp-operator
  template:
    metadata:
      labels:
        name: oadp-operator
    spec:
      serviceAccountName: oadp-operator
      containers:
        - name: oadp-operator
          # Replace this with the built image name
          image: "REPLACE_IMAGE"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "oadp-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: oadp-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: oadp-operator
    namespace: "oadp-operator"
namespace: "oadp-operator"
