apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: oadp-operator.v0.1.0
  namespace: oadp-operator
  annotations:
    capabilities: Seamless Upgrades
    containerImage: quay.io/konveyor/oadp-operator
    alm-examples: |-
      [
        {
          "apiVersion": "konveyor.openshift.io/v1alpha1",
          "kind": "Velero",
          "metadata": {
            "name": "example-velero"
            "namespace":"oadp-operator"
          },
          "spec": {
            "olm_managed": true,
            "backup_storage_locations": [
              {
                "config": {
                  "profile": "default",
                  "region": "us-east-1"
                },
                "credentials_secret_ref": {
                  "name": "cloud-credentials",
                  "namespace": "oadp-operator"
                },
                "name": "default",
                "object_storage": {
                  "bucket": "mybucket",
                  "prefix": "velero"
                },
                "provider": "aws"
              }
            ],
            "default_velero_plugins": [
              "aws"
            ],
            "enable_restic": true,
            "volume_snapshot_locations": [
              {
                "config": {
                  "profile": "default",
                  "region": "us-west-2"
                },
                "name": "default",
                "provider": "aws"
              }
            ]
          }
          {
            "apiVersion": "velero.io/v1",
            "kind": "Backup",
            "metadata": {
              "name": "backup",
              "namespace": "oadp-operator"
            },
            "spec": {}
        },
        {
            "apiVersion": "velero.io/v1",
            "kind": "BackupStorageLocation",
            "metadata": {
              "name": "backupstoragelocation",
              "namespace": "oadp-operator"
            },
            "spec": {}
        },
        {
            "apiVersion": "velero.io/v1",
            "kind": "DeleteBackupRequest",
            "metadata": {
              "name": "deletebackuprequest",
              "namespace": "oadp-operator"
            },
            "spec": {}
        },
        {
            "apiVersion": "velero.io/v1",
            "kind": "DownloadRequest",
            "metadata": {
              "name": "downloadrequest",
              "namespace": "oadp-operator"
            },
            "spec": {}
        },
        {
            "apiVersion": "velero.io/v1",
            "kind": "PodVolumeBackup",
            "metadata": {
              "name": "podvolumebackup",
              "namespace": "oadp-operator"
            },
            "spec": {}
        },
        {
            "apiVersion": "velero.io/v1",
            "kind": "PodVolumeRestore",
            "metadata": {
              "name": "podvolumerestore",
              "namespace": "oadp-operator"
            },
            "spec": {}
        },
        {
            "apiVersion": "velero.io/v1",
            "kind": "ResticRepository",
            "metadata": {
              "name": "resticrepository",
              "namespace": "oadp-operator"
            },
            "spec": {}
        },
        {
            "apiVersion": "velero.io/v1",
            "kind": "Restore",
            "metadata": {
              "name": "restore",
              "namespace": "oadp-operator"
            },
            "spec": {}
        },
        {
            "apiVersion": "velero.io/v1",
            "kind": "Schedule",
            "metadata": {
              "name": "schedule",
              "namespace": "oadp-operator"
            },
            "spec": {}
        },
        {
            "apiVersion": "velero.io/v1",
            "kind": "ServerStatusRequest",
            "metadata": {
              "name": "serverstatusrequest",
              "namespace": "oadp-operator"
            },
            "spec": {}
        },
        {
            "apiVersion": "velero.io/v1",
            "kind": "VolumeSnapshotLocation",
            "metadata": {
              "name": "volumesnapshotlocation",
              "namespace": "oadp-operator"
            },
            "spec": {}
        },
        }
      ]
    capabilities: Basic Install
    certified: "false"
    repository: https://github.com/konveyor/oadp-operator
    support: Red Hat
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Velero
      name: veleros.konveyor.openshift.io
      version: v1alpha1
  description: OADP is OpenShift Application Data Protection operator. This operator
    sets up and installs Velero on the OpenShift platform.
  displayName: OADP Operator
  maintainers: 
  - name: Red Hat
    email: deshah@redhat.com
  icon:
  - base64data: " "    
    mediatype: image/png
  install:
    spec:
      deployments:
      - name: oadp-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: oadp-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: oadp-operator
            spec:
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: oadp-operator
                - name: ANSIBLE_GATHERING
                  value: explicit
                - name: REGISTRY
                  value: quay.io
                - name: PROJECT
                  value: konveyor
                - name: VELERO_REPO
                  value: velero
                - name: VELERO_OPENSHIFT_PLUGIN_REPO
                  value: openshift-velero-plugin
                - name: VELERO_RESTIC_RESTORE_HELPER_REPO
                  value: velero-restic-restore-helper
                - name: VELERO_OPENSHIFT_PLUGIN_TAG
                  value: unified-repo
                - name: VELERO_AWS_PLUGIN_REPO
                  value: velero-plugin-for-aws
                - name: VELERO_GCP_PLUGIN_REPO
                  value: velero-plugin-for-gcp
                - name: VELERO_AZURE_PLUGIN_REPO
                  value: velero-plugin-for-microsoft-azure
                - name: VELERO_TAG
                  value: latest
                - name: VELERO_RESTIC_RESTORE_HELPER_TAG
                  value: latest
                - name: VELERO_PLUGIN_TAG
                  value: latest
                - name: VELERO_AWS_PLUGIN_TAG
                  value: latest
                - name: VELERO_GCP_PLUGIN_TAG
                  value: latest
                - name: VELERO_AZURE_PLUGIN_TAG
                  value: latest
                image: quay.io/konveyor/oadp-operator:latest
                imagePullPolicy: Always
                name: oadp-operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: oadp-operator
              volumes:
              - emptyDir: {}
                name: runner
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - oadp-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - konveyor.openshift.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - velero.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: oadp-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - velero
  links:
  - name: Oadp Operator
    url: https://oadp-operator.domain
  maintainers:
  - email: deshah@redhat.com
    name: devarsh
  maturity: alpha
  provider:
    name: redhat
  version: 0.1.0
  customresourcedefinitions:
    owned:
    - name: backupstoragelocations.velero.io
      version: v1
      kind: BackupStorageLocation
      displayName: BackupStorageLocation
      description: A velero backup storage location
    - name: backups.velero.io
      version: v1
      kind: Backup
      displayName: Backup
      description: A velero backup
    - name: deletebackuprequests.velero.io
      version: v1
      kind: DeleteBackupRequest
      displayName: DeleteBackupRequest
      description: A request to delete a velero backup
    - name: downloadrequests.velero.io
      version: v1
      kind: DownloadRequest
      displayName: DownloadRequest
      description: A download request for velero
    - name: podvolumebackups.velero.io
      version: v1
      kind: PodVolumeBackup
      displayName: PodVolumeBackup
      description: A velero pod volume backup
    - name: podvolumerestores.velero.io
      version: v1
      kind: PodVolumeRestore
      displayName: PodVolumeRestore
      description: A velero pod volume restore
    - name: resticrepositories.velero.io
      version: v1
      kind: ResticRepository
      displayName: ResticRepository
      description: A restic repository for velero
    - name: restores.velero.io
      version: v1
      kind: Restore
      displayName: Restore
      description: A velero restore
    - name: schedules.velero.io
      version: v1
      kind: Schedule
      displayName: Schedule
      description: A velero schedule
    - name: serverstatusrequests.velero.io
      version: v1
      kind: ServerStatusRequest
      displayName: ServerStatusRequest
      description: A velero server status request
    - name: volumesnapshotlocations.velero.io
      version: v1
      kind: VolumeSnapshotLocation
      displayName: VolumeSnapshotLocation
      description: A velero volume snapshot location
